# Generated by Django 4.1.2 on 2022-11-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
    ]
