# Generated by Django 4.1.2 on 2022-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(null=True, upload_to='job_logo/'),
        ),
    ]
