# Generated by Django 4.1.2 on 2023-02-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.URLField(max_length=50),
        ),
    ]
