# Generated by Django 4.1.2 on 2023-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_job_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='custom_tags',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.URLField(max_length=128),
        ),
    ]
